version: '2.2'

services:
  os:
    build:
      context: .
      dockerfile: Dockerfile.bob.template
      args:
        OS_VERSION: ${OS_VERSION:-2.48.0_rev3}
        DEVICE_TYPE: ${DEVICE_TYPE:-intel-nuc}
    privileged: true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 30s
    volumes:
      - /lib/modules:/lib/modules:ro
      - ${CONFIG_JSON:-./config.json}:/var/local/config.json
      - /mnt/boot
      - /mnt/data
      - /mnt/state
      - /sys/fs/cgroup/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/lib/journal
    network_mode: bridge
    extra_hosts:
        - "api.${BOB_TLD} vpn.${BOB_TLD} registry2.${BOB_TLD} delta.${BOB_TLD} s3.${BOB_TLD}:${BOB_IP}" #host and ip
    dns:
      - 127.0.0.2
    tty: true
