# syntax=docker/dockerfile:1.2

ARG SHA

FROM ${SHA}

COPY ./entry.sh /entry.sh
COPY ./conf/systemd-watchdog.conf /etc/systemd/system.conf.d/watchdog.conf

ENV container=docker

VOLUME /mnt/boot \
       /mnt/state \
       /mnt/data

CMD [ "/entry.sh" ]

