ARG OS_VERSION
ARG DEVICE_TYPE=%%BALENA_MACHINE_NAME%%

FROM resin/resinos:${OS_VERSION}.dev-${DEVICE_TYPE}

ENV container=docker

VOLUME /mnt/boot \
       /mnt/state \
       /mnt/data

COPY ./conf/systemd-watchdog.conf /etc/systemd/system.conf.d/watchdog.conf
COPY ./aufs2overlay.sh /aufs2overlay

CMD [ "sh", "-c", "/aufs2overlay && exec /sbin/init" ]

